### ISSUE TITLE
Query parameter exploded object serialization

### ISSUE THREAD

**Issue by LeweyM** [anttiviljami/openapi-backend#569]
Hey,

The [OpenAPI specs](https://swagger.io/docs/specification/serialization/) outline a way to serialize exploded object query parameters. This means that with a spec like the following:

```yaml
parameters:
  - in: query
    name: color
    schema:
      type: object
      items:
        properties:
            type:
              type: string
            color:
              type: string
    style: form
    explode: true
```
You should be able to make requests like so: `request?type="square"&color="red"`

This currently isn't supported by openapi-backend. Is this intentional?

If not, I'd be happy to make a PR.

Great library btw ❤️
